#!/bin/bash
# Context Refresh - Quick summary untuk AI yang lupa context

echo "=== LLM ROUTER - QUICK CONTEXT REFRESH ==="
echo ""
echo "📦 PROVIDERS (9 total):"
echo "  - kc (Kimchi): 13 keys, 13 models"
echo "  - cv (Cavoti): 4 keys, 8 models"
echo "  - bm (BluesMinds): 2 keys, 200+ models"
echo "  - nry (byNara): 2 keys, 40+ models"
echo "  - dahl: 8 keys, 3 models"
echo "  - qc (Qwen Cloud): 60 keys, 149 models"
echo "  - marketku: 1 key, 14 models"
echo "  - atomesus: 9 keys, 1 model"
echo "  - weize: 1 key, 60+ models"
echo ""
echo "🗄️ DATABASE:"
echo "  - api_keys, request_logs, chat_sessions, chat_messages"
echo ""
echo "🆕 RECENT CHANGES:"
echo "  - 2026-08-06: Conversation Memory feature deployed ✅"
echo "  - 2026-08-05: Added Weize provider"
echo "  - 2026-08-04: Fixed BluesMinds model list"
echo ""
echo "⚠️ KNOWN ISSUES:"
echo "  - ROUTER_PASSWORD disabled (blocks upstream keys)"
echo "  - MarketKu mimo-v2.5-pro needs tool definitions"
echo ""
echo "🌐 PRODUCTION:"
echo "  - URL: https://routers.iyantama.tech"
echo "  - Server: iyanserve@70.153.8.223"
echo "  - Path: /home/iyanserve/llm-router"
echo ""
echo "📊 STATS:"
docker exec llm-router-db psql -U llm_router_user -d llm_router -t -c "SELECT COUNT(*) FROM request_logs;" 2>/dev/null | xargs echo "  - Total requests:"
docker exec llm-router-db psql -U llm_router_user -d llm_router -t -c "SELECT COUNT(*) FROM chat_sessions;" 2>/dev/null | xargs echo "  - Chat sessions:"
echo ""
echo "📝 LAST 3 COMMITS:"
git log --oneline -3
echo ""
echo "=== Ready to continue development! ==="
